name: Lint and Publish
on: push
jobs:
  install: 
    name: Install Packages and Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run lint


